# This file was generated by GoReleaser. DO NOT EDIT.
class Apimation < Formula
  desc "apimation cli client"
  homepage "https://apimation.com/"
  version "0.54.0"

  if OS.mac?
    url "https://github.com/apimation/cli-client/releases/download/v0.54.0/apimation_0.54.0_macOS_amd64.zip"
    sha256 "1780bbf1c49bce24b594e945b86e83f14f0b0ba11e43929f0f3b46154406f204"
  elsif OS.linux?
    url "https://github.com/apimation/cli-client/releases/download/v0.54.0/apimation_0.54.0_linux_amd64.zip"
    sha256 "c2ba53ce6d77ce4f5211ca452e56b89de954750af37036e87f446fd8e5ccfde9"
  end
  
  depends_on "git"

  def install
    bin.install "apimation"
  end

  test do
    system "#{bin}/apimation --version"
  end
end
