# This file was generated by GoReleaser. DO NOT EDIT.
class Apimation < Formula
  desc "apimation cli client"
  homepage "https://apimation.com/"
  version "0.54.7"

  if OS.mac?
    url "https://github.com/apimation/cli-client/releases/download/v0.54.7/apimation_0.54.7_macOS_amd64.zip"
    sha256 "58a8906decdc6d5b03c6057b0979b08d42c2e3ce1e0b2541dcc0e19faa8d348b"
  elsif OS.linux?
    url "https://github.com/apimation/cli-client/releases/download/v0.54.7/apimation_0.54.7_linux_amd64.zip"
    sha256 "283d6d78eae8d29a8d52d35c30ffa6f2ef447a962b01cd3a1bef335828a9fe7b"
  end
  
  depends_on "git"

  def install
    bin.install "apimation"
  end

  test do
    system "#{bin}/apimation --version"
  end
end
