# This file was generated by GoReleaser. DO NOT EDIT.
class Apimation < Formula
  desc "apimation cli client"
  homepage "https://apimation.com/"
  version "0.54.1"

  if OS.mac?
    url "https://github.com/apimation/cli-client/releases/download/v0.54.1/apimation_0.54.1_macOS_amd64.zip"
    sha256 "c3842b3be2ed376259beb677e9a2ba50c2abf122c0705d0c67ac4057b6ffa47a"
  elsif OS.linux?
    url "https://github.com/apimation/cli-client/releases/download/v0.54.1/apimation_0.54.1_linux_amd64.zip"
    sha256 "b5c3d7a7c7e0309d722116b9c8a99bf88f08d2aa2b0cd723aa48400578c544c2"
  end
  
  depends_on "git"

  def install
    bin.install "apimation"
  end

  test do
    system "#{bin}/apimation --version"
  end
end
