# This file was generated by GoReleaser. DO NOT EDIT.
class Testengineworker < Formula
  desc "apimation test engine worker"
  homepage "https://apimation.com/"
  version "0.25.5"

  if OS.mac?
    url "https://github.com/apimation/testEngineWorker/releases/download/v0.25.5/testengineworker_0.25.5_macOS_amd64.zip"
    sha256 "ae868a80952ca361956f07354d0bae71c912d7206d98d06067c5afc00fe54d1d"
  elsif OS.linux?
    url "https://github.com/apimation/testEngineWorker/releases/download/v0.25.5/testengineworker_0.25.5_linux_amd64.zip"
    sha256 "2e9650791b2cda309c8ee53f4a18eca2d23d480830c635a2ed30715e672d8bb2"
  end
  
  depends_on "git"

  def install
    bin.install "testEngineWorker"
  end

  test do
    system "#{bin}/testEngineWorker -version"
  end
end
