# This file was generated by GoReleaser. DO NOT EDIT.
class Testengineworker < Formula
  desc "apimation test engine worker"
  homepage "https://apimation.com/"
  version "0.27.1"

  if OS.mac?
    url "https://github.com/apimation/testEngineWorker/releases/download/v0.27.1/testengineworker_0.27.1_macOS_amd64.zip"
    sha256 "1f9c3614306e13bd7449d798afdeaef584bdde8f1c185deeab6a0406d436cc59"
  elsif OS.linux?
    url "https://github.com/apimation/testEngineWorker/releases/download/v0.27.1/testengineworker_0.27.1_linux_amd64.zip"
    sha256 "07d07967a73826fe55b23165a7ba7c4d7c233adfc47483de7e793e4d05df727e"
  end
  
  depends_on "git"

  def install
    bin.install "testEngineWorker"
  end

  test do
    system "#{bin}/testEngineWorker -version"
  end
end
